[mysql_fb]
host = "homolog.cvuwkhnpr3rt.us-east-2.rds.amazonaws.com"
port = 6303
database = "EPM_FB"
username = "blue_eshows"
password = "qNK7JPwwDFdf2sQq"

[users]
emails = [
    "gabriel.cunha@eshows.com.br", 
    "joao.scabora@fabricadebares.com.br", 
    "vanessa.delsanto@fabricadebares.com.br",
    "financeiro.bardosarcos@fabricadebares.com.br",
    "financeiro.bluenote@fabricadebares.com.br",
    "financeiro.bardosarcos@fabricadebares.com.br",
    "financeirocp@fabricadebares.com.br",
    "financeiro.bluenote@fabricadebares.com.br",
    "lancamentos@fabricadebares.com.br",
    "fincentral@fabricadebares.com.br",
    "financeirocr@fabricadebares.com.br",
    "beatriz.lima@fabricadebares.com.br",
    "contabilidade.fabricadebares",
    "lucas.simon@fabricadebares.com.br",
    "luiza.carvalho@macroconsultoria.com.br",
    "fabiana.santana@macroconsultoria.com.br",
    "financeiro.cobranca@fabricadebares.com.br"
]